### ISSUE TITLE
Review 1: Algoritma (diagram alir) ada kerumitan

### ISSUE THREAD

**Issue by priyandari** [nikowahyupratama/Pengisian-BBM#1]
![Capture](https://user-images.githubusercontent.com/4914090/83822857-77cb4100-a6fc-11ea-83c8-3f9e6fc0c57d.PNG)

D keluar menuju D yang mana ? karena ada 2 D sebagai input

**Comment by RamandaBanu** [comment]
Issue ini telah kami perbaiki. Kerumitan telah diperbaiki, dapat dilihat pada revisi flowchart program pengisian BBM.
