### ISSUE TITLE
Review 1: Panduan penggunaan?

### ISSUE THREAD

**Issue by priyandari** [nikowahyupratama/Pengisian-BBM#3]
Infokan pass untuk uji coba

F:\Dropbox\01 PERKULIAHAN\Program Komputer\UAS Prokom 2020\Review 1\Pengisian-BBM-master  Fri 06/05/
2020  7:18:09.89
? python Sistem-Pengisian-BBM.py
-----------------------
    Daftar Karyawan
-----------------------
[1] Aby
[2] Alifta
[3] Banu
[4] Niko
[5] Surya
[6] Yudha
Masukkan kode karyawan: 5
Masukkan Password: 1234
AKSES DITOLAK

**Comment by RamandaBanu** [comment]
Password setiap karyawan telah ditambahkan.
