### ISSUE TITLE
Harga bisa di update

### ISSUE THREAD

**Issue by priyandari** [nikowahyupratama/Pengisian-BBM#4]
Lebih bagus kalau harga masing-masing produk bisa diupdate dan disimpan dalam file. Kemudian digunakan oleh program. Jadi setelah masuk program, ada pilihawan awal dahulu untuk update data harga BBM. kemudian menggunakan program terus menerus sampai tutup

**Comment by RamandaBanu** [comment]
Kami menambahkan file dalam format .csv untuk menyimpan data harga bbm yang nantinya dapat diupdate seiring perubahan harga di lapangan.  Kami menggunakan bantuan library pandas untuk membuka, mengolah, dan menulis ulang data.
