### ISSUE TITLE
Tambahkan report transaksi petugas

### ISSUE THREAD

**Issue by priyandari** [nikowahyupratama/Pengisian-BBM#5]
Ketika memilih keluar dari program,
Tambahkan report total  transaksi yang dilakukan oleh petugas tersebut.
COntoh
No Nama BBM     Harga/L           Total Keluar (L)            Total Transaksi
1)   Pertamax
2)   dst

TOTAL SELURUH TRANSAKSI

**Comment by RamandaBanu** [comment]
Kami menggunakan library pandas untuk mengolah dan menampilkan rekap transaksi.
